### ISSUE TITLE
Deceptive formatting for arguments of trig and log functions involving multiplication

### ISSUE THREAD

**Issue by dlglin** [openwebwork/mathquill#10]
This may not be considered a bug, but when a student types something like "ln4x" MQ adds space between the operator ln and the 4x, but there is no space between the 4 and the x.  This makes it look to the student like 4x is the argument of ln, whereas WW interprets this as ln(4)x (and in fact shows that when previewing or submitting answers).

Would it be clearer if there were space between the 4 and the x?  Is that even possible to do in a reliable way, since that space wouldn't be necessary in most other contexts?

<img width="1148" alt="Argument of ln in MQ" src="https://user-images.githubusercontent.com/1794586/221263573-963d0472-03f7-4e36-9410-a1c927a82787.png">

**Comment by drgrice1** [comment]
Unfortunately, I don't see any way to reliably do that.  This is one of those cases that WeBWorK differs from most systems on.  Most mathematical systems would interpret ln4x as ln(4x).

What I want to do, and have worked on a bit with is to always add parentheses when functions like `ln`, `sin`, `cos`, etc., are typed.

**Comment by drgrice1** [comment]
I believe that this issue was fixed with the `MathFunction` added in #12.  So I am closing it.
