### ISSUE TITLE
not equals

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/mathquill#18]
If a student uses ≠ in an answer with MathQuill enabled, for example with `x≠0` the submitted answer has `ne`, as in `xne0`. And WeBWorK of course does not understand this.

Probably it should submit `x!=0`. Depending on WeBWorK/PG config, it would be OK to submit `x≠0` too.

My server is configured to allow `x≠0`, assuming the MathObject context of the answer understands that character. And this works fine with MQ not enabled. But a student rand into this issue while MQ is enabled. (And overlooked the explicit instructions to type `!=`).

**Comment by Alex-Jordan** [comment]
I'm looking at how to add `!=` as a MQ operator. This would not be semantically correct, but it looks like it might fit as a "not strict" `Inequality` (in `src/commands/math/basicSymbols.ts`) because what really matters about those is that they are made of two characters. 

Or maybe it should be added as a new kind of `Equality` that handles the two characters like "not strict" `Inequality` does with `<=` and `>=`.

Or maybe it's just a new extension of `BinaryOperator` altogether.

**Comment by drgrice1** [comment]
I will look into this.  I think that a "not strict" `Inequality` will work.  The `ne` case in `src/commands/math/advancedSymbols.ts` will probably need to be replaced with whatever we go with.

**Comment by pstaabp** [comment]
Added in #20
